version: '2'
services:
  sonarqube:
    image: "sonarqube:5.3"
    hostname: sonarqube
    restart: always
    ports:
     - "9000:9000"
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
     - SERVICE_NAME=sonarqube
    networks:
      - sonar-net
    depends_on: sonar-db
  sonar-db:
    image: postgres
    hostname: sonar-db
    environment:
     - SERVICE_NAME=sonar-db
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar
     - PGDATA=/var/lib/postgresql/data/sonar-data
    volumes:
      - sonar-data:/var/lib/postgresql/data/sonar-data
    networks:
      - sonar-net
volumes:
  sonar-data:
    driver: local
networks:
  sonar-net:
    driver: bridge
