version: '2'
services:
  haproxy:
    build: haproxy/
    image: docker.kiwigrid.com/joern.schwarze/alm-haproxy:latest
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
    ## If you want to override the haproxy config from outside of the container.
    # volumes:
    #   - ~/projects/docker/ha-proxy/haproxy.cfg://usr/local/etc/haproxy/haproxy.cfg
    restart: always
    networks:
      - alm-net
  jenkins:
    build: jenkins/
    image: docker.kiwigrid.com/joern.schwarze/alm-jenkins:latest
    expose:
     - "8080"
     - "50000"
    restart: always
    networks:
      - alm-net
  nexus:
    build: nexus/
    image: docker.kiwigrid.com/joern.schwarze/alm-nexus:latest
    command: run
    expose:
      - "8081"
    restart: always
    networks:
      - alm-net
  bitbucket:
    build: bitbucket/
    image: docker.kiwigrid.com/joern.schwarze/alm-bitbucket:latest
    expose:
     - "8080"
    restart: always
    networks:
      - alm-net
  sonarqube:
    image: "sonarqube:5.4"
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
    restart: always
    networks:
      - alm-net
  sonar-db:
    image: postgres
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar
     - PGDATA=/var/lib/postgresql/data/sonar-data
    restart: always
    networks:
      - alm-net
networks:
  alm-net:
    driver: bridge
