nexus:
  build: nexus
  hostname: nexus
  command: run
  environment:
    - SERVICE_NAME=nexus
    - SERVICE_TAGS=alm,maven
  ports:
   - "8081:8081"
bitbucket:
  build: bitbucket
  hostname: bitbucket
  ports:
   - "7990:7990"
  environment:
   - SERVICE_NAME=bitbucket
crowd:
  build: crowd
  hostname: crowd
  ports: 8080:8080
  environment:
   - SERVICE_NAME=crowd
sonarqube:
  image: "sonarqube:5.3"
  hostname: sonarqube
  ports:
   - "9000:9000"
  links:
   - sonar-db:db
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db.service.kiwicloud:5432/sonar
   - SERVICE_NAME=sonarqube
sonar-db:
  image: postgres
  hostname: sonar-db
  environment:
   - SERVICE_NAME=sonar-db
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
  ports:
   - "5432:5432"
