nexus:
  container_name: nexus
  build: nexus
  hostname: nexus
  command: run
  environment:
    - SERVICE_NAME=nexus
    - SERVICE_TAGS=alm,maven
bitbucket:
  build: bitbucket
  hostname: bitbucket
  environment:
   - SERVICE_NAME=bitbucket
crowd:
  build: crowd
  hostname: crowd
  environment:
   - SERVICE_NAME=crowd
sonarqube:
  image: "sonarqube:5.3"
  hostname: sonarqube
  links:
   - sonar-db:db
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
   - SERVICE_NAME=sonarqube
sonar-db:
  image: postgres
  hostname: sonar-db
  environment:
   - SERVICE_NAME=sonar-db
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
nginx:
  build: nginx
  environment:
    - SERVICE_NAME=nginx
    - NEXUS_HOST=nexus
  links:
    - sonarqube:sonar
    - bitbucket:bitbucket
    - crowd:crowd
    - nexus:nexus