version: '2'
services:
  haproxy:
    build: ../haproxy/
    image: docker.kiwigrid.com/joern.schwarze/alm-haproxy:latest
    ports:
      - "443:443"
      - "80:80"
    ## If you want to override the haproxy config from outside of the container.
    # volumes:
    #   - ~/projects/docker/ha-proxy/haproxy.cfg://usr/local/etc/haproxy/haproxy.cfg
    networks:
      - alm-net
  jenkins:
    build: ../jenkins/
    image: docker.kiwigrid.com/joern.schwarze/alm-jenkins:latest
    expose:
     - "8080"
     - "50000"
    networks:
      - alm-net
  nexus:
    build: ../nexus/
    image: docker.kiwigrid.com/joern.schwarze/alm-nexus:latest
    command: run
    expose:
      - "8081"
    networks:
      - alm-net
  jenkins:
    build: ../bitbucket/
    image: docker.kiwigrid.com/joern.schwarze/alm-bitbucket:latest
    expose:
     - "7990"
    networks:
      - alm-net
  sonarqube:
    image: "sonarqube:5.4"
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
    networks:
      - alm-net
  sonar-db:
    image: postgres
    networks:
      - alm-net
networks:
  alm-net:
    driver: bridge
